# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Jarvis' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jarvis
  pod 'GoogleMLKit/Translate', '3.2.0'

  target 'JarvisTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JarvisUITests' do
    # Pods for testing
  end

end
